import dev.practice.drools.Freedom;
import dev.practice.drools.jpa.entity.ValidationControl;
import dev.practice.drools.jpa.entity.ValidationErrors;

import function dev.practice.util.DroolsUtil.help;

rule "100"
	when
	exists ValidationControl(validationNo == 1)
	Freedom($state : state in ("", " ", null))
then
    ValidationErrors error = new ValidationErrors();
    error.setErrorSeqNbr(2);
    error.setErrorMsg("state is empty");
    error.setCreatedBy("Reddy");
    error.setCreatedDate(16082015);
    error.setCreatedTime(1646);
    System.out.println("Rule 100: "+error.getCreatedBy());
    help(drools,"Added DroolsUtil..");
end


