import com.practice.drools.Freedom;
import com.practice.drools.jpa.entity.ValidationControl;
import com.practice.drools.jpa.entity.ValidationErrors;

rule "001"
	when
	exists ValidationControl(validationNo == 1)
	Freedom($state : state in ("", " ", null))
	//eval($state.isEmpty())
then
    ValidationErrors error = new ValidationErrors();
    error.setErrorSeqNbr(1);
    error.setErrorMsg("state is empty");
    error.setCreatedBy("Reddy");
    error.setCreatedDate(16082015);
    error.setCreatedTime(1646);
    System.out.println(error.getErrorMsg());
end

